// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj2rggl2f_Tg3QN6NudN3x5dTOQBREfRI',
    appId: '1:387707124923:web:b6c1379c112b4e8162bd9e',
    messagingSenderId: '387707124923',
    projectId: 'say-it-a35a2',
    authDomain: 'say-it-a35a2.firebaseapp.com',
    storageBucket: 'say-it-a35a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYC93bh84swML75ACSuimqJJ2yEtri6vo',
    appId: '1:387707124923:android:dc9e3ae5cadae84e62bd9e',
    messagingSenderId: '387707124923',
    projectId: 'say-it-a35a2',
    storageBucket: 'say-it-a35a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSvkIu_3iN3N68xkLEhGsJkt33fXAKFQs',
    appId: '1:387707124923:ios:12759e38b0d03b8c62bd9e',
    messagingSenderId: '387707124923',
    projectId: 'say-it-a35a2',
    storageBucket: 'say-it-a35a2.appspot.com',
    iosClientId: '387707124923-4m1ld9l5iiou5rn7rt7civh8136cfbnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sayIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSvkIu_3iN3N68xkLEhGsJkt33fXAKFQs',
    appId: '1:387707124923:ios:12759e38b0d03b8c62bd9e',
    messagingSenderId: '387707124923',
    projectId: 'say-it-a35a2',
    storageBucket: 'say-it-a35a2.appspot.com',
    iosClientId: '387707124923-4m1ld9l5iiou5rn7rt7civh8136cfbnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sayIt',
  );
}
